# use version 3 of the docker compose syntax
version: '3'
services:
  # we named our first service 'web'
    web:
        # passing a hostname to the container (optinal)
        hostname: apiexample.pro

        # build a custom image
        build:
          context: .
          dockerfile: Dockerfile

        # a name for easier reference
        image: apiexample
        container_name: web
        # map host port 8080 to container port 80
        ports:
            - 8080:80
        environment:
            - VIRTUAL_HOST=apiexample.com

        volumes:
          - /var/www/html
        # first load the 'db' service
        networks:
            - new
        depends_on:
          - mysql

    mysql:
        # use a default image
        image: mysql:5.6

        container_name: mysql

        networks:
              new:
                aliases:
                  - mysql
        restart: always

        volumes:
          - ./database:/docker-entrypoint-initdb.d
        # again, port mapping
        ports:
          - 13306:3306

        # the mysql image uses these to create database and users
        environment:
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: apitest
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_PASSWORD:

networks:
    new:
      driver: bridge

